#!/bin/bash -e

filename=$(mktemp)
s3filename="${AWS_S3_FILE_PREFIX}-$(date +%s).sql"

mysqldump -h "${MYSQL_HOST}" -P "${MYSQL_PORT}" -u "${MYSQL_USER}" -p"${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" > "${filename}"

aws s3 cp "${filename}" "s3://${AWS_S3_BUCKET}/${s3filename}"

rm -rf filename
